# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cdc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cdc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcdc.proto\x12\x03\x63\x64\x63\"d\n\x0c\x43hangeRecord\x12\x0b\n\x03lsn\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_time\x18\x02 \x01(\x03\x12\r\n\x05table\x18\x03 \x01(\t\x12\x11\n\toperation\x18\x04 \x01(\t\x12\x10\n\x08raw_data\x18\x05 \x01(\t\"W\n\rReplayRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12 \n\x05\x65vent\x18\x02 \x01(\x0b\x32\x11.cdc.ChangeRecord\x12\x14\n\x0cvirtual_time\x18\x03 \x01(\x03\"2\n\x0eReplayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\x08Replayer\x12\x36\n\x0bReplayEvent\x12\x12.cdc.ReplayRequest\x1a\x13.cdc.ReplayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cdc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGERECORD']._serialized_start=18
  _globals['_CHANGERECORD']._serialized_end=118
  _globals['_REPLAYREQUEST']._serialized_start=120
  _globals['_REPLAYREQUEST']._serialized_end=207
  _globals['_REPLAYRESPONSE']._serialized_start=209
  _globals['_REPLAYRESPONSE']._serialized_end=259
  _globals['_REPLAYER']._serialized_start=261
  _globals['_REPLAYER']._serialized_end=327
# @@protoc_insertion_point(module_scope)
